### ISSUE TITLE
[Question] How does this mod interact with FutureMC?

### ISSUE THREAD

**Issue by SlayerTheChikken** [jbredwards/Subaquatic#12]
FutureMC adds the same fish this mod does for example, is this mod compatible with FutureMC if I were to disable it's fish?

**Comment by jbredwards** [comment]
I don't see any reason why it shouldn't be, but if you notice any bugs relating to FutureMC mod compatibility definitely let me know :)

**Comment by SlayerTheChikken** [comment]
I will, thank you
