### ISSUE TITLE
[Bug] The underwater ambience loop sometimes stops playing randomly

### ISSUE THREAD

**Issue by Turkey9002** [jbredwards/Subaquatic#17]
The underwater ambience that plays while you're underwater will sometimes stop playing at random and you would have to reset it by going back up to the surface and back down underwater for it to play again.

**Comment by MagmaSlime123** [comment]
Aqua Acrobatics also includes this. A toggle for this mood's sound would be nice.

**Comment by jbredwards** [comment]
> Aqua Acrobatics also includes this.

I checked this before I added the feature (I also thought aqua acrobatics would have it), but it actually doesn't

**Comment by MagmaSlime123** [comment]
Ah.

**Comment by jbredwards** [comment]
fixed in v1.1.0
