### ISSUE TITLE
AssetMover doesn't like Prism Launcher.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Subaquatic#18]
Title. If this mod and AM are installed, the game crashes.

https://pastebin.com/CB367umJ

**Comment by jbredwards** [comment]
do you have fluidlogged api installed?

**Comment by MagmaSlime123** [comment]
Resolved via Discord. I didn't, but I'm not sure why this mod gives a very obscure crash that has no info.

**Comment by jbredwards** [comment]
the crash log mentions this: `Caused by: java.lang.NoClassDefFoundError: git/jbredwards/fluidlogged_api/api/asm/BasicLoadingPlugin`, which is what lead me to think you were missing fluidlogged api

**Comment by MagmaSlime123** [comment]
Ah. Not sure why a dependency warning can't be added.
