### ISSUE TITLE
Textures don't work the first time the mod is installed.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Subaquatic#20]
Title.

![image](https://user-images.githubusercontent.com/51277766/223519672-7d5d8a3d-fd0e-4fae-a488-ba89b9d5977e.png)

After manually using F3+T, they show up like normal.

![image](https://user-images.githubusercontent.com/51277766/223519919-f72e6a2f-a03d-4ec1-84f3-dc00ac0833e3.png)

This might cause issues with #11.

**Comment by jbredwards** [comment]
This looks like an assetmover bug, please create an issue on that mod's [bug tracker](https://github.com/CleanroomMC/AssetMover/issues). Until it gets resolved, try using assetmover v1.1

**Comment by MagmaSlime123** [comment]
I'm not sure what to say if I opened an issue though.
