### ISSUE TITLE
Causes some nasty FPS lag.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Subaquatic#23]
Title. If this mod is loaded, my FPS is very low, even if I'm not near any water.

My modlist:

![image](https://user-images.githubusercontent.com/51277766/223541242-3401a633-5b5d-410e-b223-0fce67073d50.png)

**Comment by jbredwards** [comment]
try adding censoredasm & nothirium

**Comment by MagmaSlime123** [comment]
Tried Nothirium, same issue. CensoredASM hates DynamicTrees and seems to be dead (7 months since any commit), so I'm not really sure what to do, and I'm not sure why this mod causes FPS issues though, it could probably be optimized to not.

**Comment by jbredwards** [comment]
a fork of dynamic trees exists called [dramatic trees](https://www.curseforge.com/minecraft/mc-mods/dramatictrees), trying the fork + censoredasm and I can't find any problems

**Comment by MagmaBro123** [comment]
Huh, didn't know that mod existed. Does it support other Dynamic Trees addons?

**Comment by MagmaSlime123** [comment]
Tried both mods, same issue. It's your mod causing the lag.

![image](https://user-images.githubusercontent.com/51277766/223590928-2a38d71b-3431-4f77-92a9-57805fff5dc5.png)

Nothirium does say that a certain setting in LoliASM needs to be disabled, but that still crashes, making Nothirium useless anyway.

**Comment by jbredwards** [comment]
send a [spark](https://beta.curseforge.com/minecraft/mc-mods/spark) profile

**Comment by MagmaSlime123** [comment]
https://spark.lucko.me/YkpvZvd1pL

LoliASM requires 1.5.2. Don't mind the warning it gives

**Comment by jbredwards** [comment]
> Nothirium does say that a certain setting in LoliASM needs to be disabled, but that still crashes, making Nothirium useless anyway.

Nothirium needs a mod called RenderLib to function

**Comment by MagmaSlime123** [comment]
Ah, my bad. Anyway, does the report help?

**Comment by jbredwards** [comment]
yes actually, I think it could be caused by fluidlogged api's fluid collision. Does this ([Fluidlogged-API-v2.1.0-mc1.12.2.zip](https://github.com/jbredwards/Subaquatic/files/10925960/Fluidlogged-API-v2.1.0-mc1.12.2.zip)) help? (remember to extract the file, git doesn't support the .jar file type) If the fix helps I'll upload it to curseforge.

**Comment by MagmaSlime123** [comment]
Sorry for the late response, testing now.

Edit: Lag seems to be quite a bit better, but there are still some minor stutters here n' there.
Edit 2: Nothirium does seem to make the stuttering worse though, so I'm not gonna use it, unless its FluidloggedAPI being dumb with it.
Edit 3: Decided to run Spark again with Nothirium + that FluidloggedAPI version, just in case. https://spark.lucko.me/DxS015bhxE

**Comment by jbredwards** [comment]
glad it helped! I am seeing some light lag though, re-adding Hesperus (the phosphor fork) should help with that. I don't see anything in there pointing to subaquatic or fluidlogged api anymore so I'm marking this as fixed

**Comment by MagmaSlime123** [comment]
Ah, alright. I'll ping you here if this ever pops up again.
