### ISSUE TITLE
[Suggestion] Deep Warm Oceans

### ISSUE THREAD

**Issue by Turkey9002** [jbredwards/Subaquatic#24]
It was a previously unused biome until finally getting the cut in 1.18. Deeper coral reefs should be a thing, you could do something cool with it like this [mod ](https://www.planetminecraft.com/mod/deep-warm-ocean/)does.

**Comment by jbredwards** [comment]
this mod does have deep warm ocean biomes, though they had some inconsistencies with their shallow warm ocean counterparts (no coral spawned, nor did tropical fish), fixed in v1.1.0!
