### ISSUE TITLE
Leaves convert grass block to dirt

### ISSUE THREAD

**Issue by wed15** [jbredwards/Subaquatic#25]
With Subaquatic mod installed, leaves convert grass block to dirt as if they are solid block. This also happens with other modded blocks which inherit properties of leaves block.

Screenshot featuring berry bushes from Rustic mod and vanilla oak leaves:
![2023-03-10_00 57 14](https://user-images.githubusercontent.com/86100898/224088737-7111499f-d80a-4442-9b7e-dee536d1a2c7.png)

**Mod Versions**
Subaquatic-v1.0.1-mc1.12.2
Fluidlogged-API-v2.1.0-mc1.12.2

**Comment by jbredwards** [comment]
fixed in v1.1.0
