### ISSUE TITLE
Add option to easily use vanilla colors for vanilla biomes

### ISSUE THREAD

**Issue by embeddedt** [jbredwards/Subaquatic#27]
The default water color Subaquatic uses for vanilla biomes like the river or plains seems to differ from vanilla (seems closer to the Bedrock color at first glance). I am aware that there is a config to change that but it would be nice to have an easy way to use the 1.13 colors. Normally Aqua Acrobatics does that but it seems that your ASM transformer forcefully disables it.

![2023-03-22_11 24 34](https://user-images.githubusercontent.com/42941056/226953736-43f5e975-5721-4b84-b5ca-7f58ebce3e44.png)

**Comment by MagmaSlime123** [comment]
If Aqua Acrobatics  support is added then this wouldn't be an issue. Mod seems inactive.

**Comment by jbredwards** [comment]
This mod unfortunately has to disable AA's fluid colors, because this mod adds biomes with their own 1.13 water colors. I did replace the bedrock ocean & forest water colors with the java edition ones though in v1.1.0!

> If Aqua Acrobatics support is added then this wouldn't be an issue. Mod seems inactive.

This mod does have AA support, I've just been busy.

**Comment by embeddedt** [comment]
Perfect. AA uses the Java 1.13 water colors anyway so it won't be a visible difference.
