### ISSUE TITLE
Can‘t compile

### ISSUE THREAD

**Issue by zeng-github01** [jbredwards/Subaquatic#28]
https://dvs1.progwml6.com website no longer contains mcp files

![image](https://user-images.githubusercontent.com/95841646/227817253-7575d830-bf74-43c0-afe1-8c00ac1f1766.png)

**Comment by jbredwards** [comment]
The only thing this mod is using that for is JEI, which is still there. https://dvs1.progwml6.com/files/maven/mezz/jei/jei_1.12.2/
If you can't get subaquatic to compile, you're having a different problem, can you send the exact error?

**Comment by zeng-github01** [comment]
Not this one......

Please update the jar file on CurseForge

jbredwards ***@***.***> 于 2023年3月28日周二 05:12写道：

**Comment by zeng-github01** [comment]
Please update the jar file on CurseForge

**Comment by zeng-github01** [comment]
Sorry, it has been confirmed as a network problem. Compiles fine with global proxy.
