### ISSUE TITLE
No texture nor sound show up in the game after being load during the startup

### ISSUE THREAD

**Issue by Tuijui** [jbredwards/Subaquatic#30]
I saw the assets load during the startup but no folder was create and no texture show up. Subaquatic itself seems to work find, and Assetmover is already at v 2.5. I removeed every other mods from folder so it couldn't be a mod conflict issue.

**Comment by jbredwards** [comment]
this sounds like an AssetMover problem, please create an issue on their issue tracker (linked [here](https://github.com/CleanroomMC/AssetMover/issues))
