### ISSUE TITLE
[Compatibility] Crafting Celestial Crystal Clusters/Fluid Crafting 

### ISSUE THREAD

**Issue by MorphoKnight** [jbredwards/Subaquatic#31]
I believe this mod's feature of causing items to float up to the top is stopping me from making Astral Sorcery Celestial Crystal Clusters. This issue could be remedied by maybe making a blacklist so that specific items sink in water (the liquid starlight is essentially just water but with a few extra properties).

(This bug could also be caused by Fluidlogged API)

**Comment by jbredwards** [comment]
fixed in v1.1.0
