### ISSUE TITLE
[Compatibility] Grey Water

### ISSUE THREAD

**Issue by MorphoKnight** [jbredwards/Subaquatic#32]
(Note: Assuming this mod is the culprit, not 100% sure)

Minor issue, but water in certain biomes in the twilight forest (ex: Mushroom Forest) is showing up as grey. This also happens in the petal apothecary from Botania. (This may be occuring due to the phosphor lighting engine as well, or it's fork, as this used to happen in the Thaumcraft crucible, but updating from the original phosphor to the updated fork fixed it.)

**Comment by jbredwards** [comment]
fixed in v1.1.0
