### ISSUE TITLE
Some soft crash issue.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Subaquatic#33]
Title. The world will randomly freeze, and requires the user to kill the game via Task Manager (Windows). I noticed this error within the log file: https://pastebin.com/Xb28MTMK.

Fastutil, SubaquaticWaterColorConfig, and the Nothirium mod (near the bottom) are all mentioned. Along with a whole bunch of other weird stuff. May be yet another Nothirium issue.

**Comment by jbredwards** [comment]
duplicate of https://github.com/jbredwards/Subaquatic/issues/22

**Comment by MagmaSlime123** [comment]
This is still ocurring on the latest version.

https://pastebin.com/0UTv9pit

**Comment by jbredwards** [comment]
fixed in v1.2.0
