### ISSUE TITLE
GeographiCraft stops this mod's biomes from generating.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Subaquatic#35]
Title, no other mods present, also required for RTG to support BOP biomes, see #19.

**Comment by jbredwards** [comment]
fixed in v1.2.0

**Comment by MagmaBro123** [comment]
Still happens.

**Comment by MagmaSlime123** [comment]
Same issue.

![image](https://github.com/jbredwards/Subaquatic/assets/51277766/a0b3261e-eb6a-4a14-8332-2c5c48445d0b)

If you need any configs, let me know.

**Comment by MagmaSlime123** [comment]
@jbredwards ^
