### ISSUE TITLE
Minecraft fails to start with mod + dependencies

### ISSUE THREAD

**Issue by tribes33** [jbredwards/Subaquatic#36]
Installed Subaquatic with its dependencies and it doesn't seem to launch, it doesn't even get into the game, this is the modlist from the MultiMC log so there is definitely a compatiblity problem with one of these mods but I think its a given considering the amount of them

[✔️] !mixinbooter-5.0.jar
  [✔️] _MixinBootstrap-1.1.0 (1).jar
  [✔️] 1.12.1-HardLib-v7.jar
  [✔️] aether-1.12.2-v1.5.3.2.jar
  [✔️] AIImprovements-1.12.1-0.0.1b1.jar
  [✔️] AIReducer-1.12.2-0.3.0.jar
  [✔️] allay-1-12.jar
  [✔️] ancientbeasts-1.9.15.jar
  [✔️] antiqueatlas-1.12.2-4.6.3.jar
  [✔️] Aquatic+Odyssey+Tropical+Tundra+the+2nd+wave+V2.2.3.jar
  [✔️] armorplus-1.12.2-11.23.0.59.jar
  [✔️] AutoRegLib-1.3-24.jar
  [✔️] AutoSwitch-v5.6.2-mc1.12.2.jar
  [✔️] base-1.12.2-3.12.1.jar
  [✔️] Baubles-1.12-1.5.2.jar
  [✔️] betterbiomeblend-1.12.2-1.1.7-forge.jar
  [✔️] bettercaves-1.12.2-2.0.4.jar
  [✔️] BetterCombat-1.12.2-1.5.6.jar
  [✔️] betterf3-1.12.2-1.0.jar
  [✔️] BetterFps-1.4.8.jar
  [✔️] BetterMineshaftsForge-1.12.2-2.2.1.jar
  [✔️] betternether-0.1.8.6.jar
  [✔️] BetterPlacement-1.0.0-1.jar
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar
  [✔️] BloodMagic-1.12.2-2.4.3-105.jar
  [✔️] blue_skies-1.12.2-v1.1.3.jar
  [✔️] Bookshelf-1.12.2-2.3.581.jar
  [✔️] Born+In+A+Barn+V1.8-1.12-1.1.jar
  [✔️] Bountiful+Baubles-1.12.2-0.1.8.jar
  [✔️] callablehorses-1.12.2-1.1.1.jar
  [✔️] ChestTransporter-1.12.2-2.8.8.jar
  [✔️] ChunkAnimator-1.12.2-1.2.1.jar
  [✔️] classicbar-0.5.4.jar
  [✔️] ClassicCombat-1.12-1.0.0.jar
  [✔️] Clumps-3.1.2.jar
  [✔️] collective-1.12.2-3.0.jar
  [✔️] colytra-1.12.2-1.2.0.4.jar
  [✔️] comforts-1.12.2-1.4.1.3.jar
  [✔️] coroutil-1.12.1-1.2.37.jar
  [✔️] CreativeCore_v1.10.70_mc1.12.2.jar
  [✔️] CTM-MC1.12.2-0.3.3.22.jar
  [✔️] Customized-Dungeon-Loot-1.12+-(v.1.0.3).jar
  [✔️] cxlibrary-1.12.1-1.6.1.jar
  [✔️] dailies-1.12.2-6.jar
  [✔️] DamageTilt-1.12.2-0.1.0.jar
  [✔️] DarkUtils-1.12.2-1.8.226.jar
  [✔️] DoggyTalents-1.12.2-1.15.1.6.jar
  [✔️] DoomlikeDungeons-1.12.5-MC1.12.2.jar
  [✔️] DoubleSlabs-1.12-0.12.2.jar
  [✔️] dragonenchantments-1.0.0.jar
  [✔️] DynamicSurroundings-1.12.2-3.5.4.2BETA.jar
  [✔️] ElectroblobsWizardry-4.3.9.jar
  [✔️] EnchantingPlus-1.12.2-5.0.174.jar
  [✔️] EnchantmentDescriptions-1.12.2-1.1.20.jar
  [✔️] enhancedarmaments-1.3.21.jar
  [✔️] EntityCulling-1.12.2-6.3.0.jar
  [✔️] EntityDesyncFix-1.12.2-1.0.2.jar
  [✔️] EquipmentCompare-1.12.2-1.3.3.jar
  [✔️] Erebus-1.0.25.jar
  [✔️] ExtendedDays-1.12.2-0.2.9-28.jar
  [✔️] FamiliarFauna-1.12.2-1.0.11.jar
  [✔️] FastFurnace-1.12.2-1.3.1.jar
  [✔️] FastWorkbench-1.12.2-1.7.2.jar
  [✔️] Fish's+Undead+Rising-1.3.3.jar
  [✔️] foamfix-0.10.5-1.12.2.jar
  [✔️] FoodExpansion1.3.3-1.12.2.jar
  [✔️] Forgelin-1.8.2.jar
  [✔️] future-mc-0.2.11.jar
  [✔️] Glymworld-PillagerOutpost-v1.1.0.jar
  [✔️] GottschCore-mc1.12.2-f14.23.5.2859-v1.15.0.jar
  [✔️] gravestone-1.10.3.jar
  [✔️] GrimoireOfGaia3-1.12.2-1.7.2.jar
  [✔️] guardillagers-1.12.2-1.0.1.jar
  [✔️] Guide-API-1.12-2.1.8-63.jar
  [✔️] hitindication-1.12.2-1.1.3.jar
  [✔️] hole_filler_mod-1.2.4.1-mc_1.12.2-forge.jar
  [✔️] hunterillager-1.12.2-1.2.jar
  [✔️] iChunUtil-1.12.2-7.2.2.jar
  [✔️] IllagersPlus-1.12.2-1.1.3.jar
  [✔️] ImprovedBackpacks-1.12.2-1.5.0.0.jar
  [✔️] InfernalMobs-1.12.1.jar
  [✔️] inventorypets-1.12-2.0.1 (1).jar
  [✔️] InventoryTweaks-1.63.jar
  [✔️] ironchest-1.12.2-7.0.54.838.jar
  [✔️] IvToolkit-1.3.3-1.12.jar
  [✔️] jei_1.12.2-4.16.1.302.jar
  [✔️] JRFTL[1.12.2]-1.1.jar
  [✔️] JustEnoughResources-1.12.2-0.8.5.27 (1).jar
  [✔️] lazydfu-agent-1.0.0.jar
  [✔️] LegendaryTooltips-1.12.2-1.1.8.jar
  [✔️] letmedespawn-1.12.2-forge-1.0.2.jar
  [✔️] Level+Up!+2-1.1.22-1.12.jar
  [✔️] leveluphp-1.12.2-1.4.0.jar
  [✔️] llibrary-1.7.19-1.12.2.jar
  [✔️] loliasm-5.6.jar
  [✔️] LunatriusCore-1.12.2-1.2.0.42-universal.jar
  [✔️] lycanitesmobs-1.12.2-2.0.8.5.jar
  [✔️] MobDismemberment-1.12.2-7.0.0.jar
  [✔️] MoBends_1.12.2-1.2.1-19.12.21.jar
  [✔️] More+Mobs+1.12.2.jar
  [✔️] MoreFurnaces-1.12.2-1.10.6.jar
  [✔️] MouseTweaks-2.10.1-mc1.12.2.jar
  [✔️] mowziesmobs-1.5.4.jar
  [✔️] multimob-1.0.5.jar
  [✔️] MultithreadedNoise-1.12.2-0.0.2.jar
  [✔️] Neat 1.4-17.jar
  [✔️] NoMoreRecipeConflict-0.12(1.12.2).jar
  [✔️] noRecipeBook_v1.2.2formc1.12.2.jar
  [✔️] Nothirium-1.12.2-0.2.4-beta.jar
  [✔️] OpenTerrainGenerator-1.12.2-v9.3.jar
  [✔️] OptiFine_1.12.2_HD_U_F5.jar
  [✔️] OreLib-1.12.2-3.5.2.2.jar
  [✔️] Pam's+HarvestCraft+1.12.2zg.jar
  [✔️] particleculling-1.12.2-v1.3.1.jar
  [✔️] performant-1.11.jar
  [✔️] phosphor-1.12.2-0.2.6+build50-universal.jar
  [✔️] PillagePlunder_1.12.2_[BETA]0.1.0.jar
  [✔️] Placebo-1.12.2-1.5.1.jar
  [✔️] PotionCore-1.9_for_1.12.2.jar
  [✔️] potiondescriptions-1.12.2-1.2.4.jar
  [✔️] Quark-r1.5-144.jar
  [✔️] ReachFix-1.12.2-1.0.5.jar
  [✔️] reap-1.5.3.jar
  [✔️] RecurrentComplex-1.4.8.2.jar
  [✔️] Regrowth-1.12.2-0.0.1.1.jar
  [✔️] Reliquary-1.12.2-1.3.4.780.jar
  [✔️] RenderLib-1.12.2-1.2.8.jar
  [✔️] replant1.12.2-1.0.0.jar
  [✔️] Rex's-AdditionalStructures-1.12.x(v.2.5.0).jar
  [✔️] RikMuldsCore_1.3.3.jar
  [✔️] RLArtifacts-1.1.2.jar
  [✔️] RLTweaker-1.12.2-0.5.3.jar
  [✔️] RoguelikeDungeonsFnarEdition-1.12.2-2.4.1.jar
  [✔️] roughmobs2-1.12.2_2.0.12.jar
  [✔️] Ruins-1.12.2.jar
  [✔️] rustic-1.1.7.jar
  [✔️] savemystronghold-1.12.2-1.0.0.jar
  [✔️] ShadowMC-1.12-3.8.0.jar
  [✔️] ShieldBreak-1.1.2.jar
  [✔️] SilentLib-1.12.2-3.0.13+167.jar
  [✔️] SmoothFont-mc1.12.2-2.0.jar
  [✔️] Sound-Physics-1.12.2-1.0.9.jar
  [✔️] SpartanShields-1.12.2-1.5.4.jar
  [✔️] SpartanWeaponry-1.12.2-beta-1.3.8.jar
  [✔️] spiders-2.0-1.12.2-1.0.3.jar
  [✔️] Stackie-1.12.2-1.6.0.48-universal.jar
  [✔️] Surge-1.12.2-2.0.77.jar
  [✔️] Swamp_1.12.2_2.6.jar
  [✔️] ThebombzenAPI-v2.9.3-mc1.12.2.jar
  [✔️] thedragonlib-1.12.2-5.3.0.jar
  [✔️] TheSpotlightMod-1.2.0.101-mc1.12.2-universal.jar
  [✔️] Toast Control-1.12.2-1.8.0.jar
  [✔️] ToroQuest-Revamped-3-25-2022.jar
  [✔️] Treasure2-mc1.12.2-f14.23.5.2859-v2.1.0.jar
  [✔️] TreeChopper-1.12.2-1.2.4.jar
  [✔️] Trinkets+and+Baubles-0.31.4.jar
  [✔️] Unique+Enchantments+Base-1.12.2-1.1.4.jar
  [✔️] Unique+Enchantments-1.12.2-2.1.4.jar
  [✔️] unloader-1.2.0.jar
  [✔️] VillageNames-1.12.2-4.4.6.jar)
  [✔️] villagermarkers-1.12.2-1.0.5.jar
  [✔️] VillagerTrades-1.12-0.6.4.jar
  [✔️] Waystones_1.12.2-4.0.67.jar
  [✔️] wonderful-enchantments-1.12.2-0.6.0.jar

**Comment by jbredwards** [comment]
send the full log (preferably via https://mclo.gs)

**Comment by tribes33** [comment]
https://mclo.gs/DKDNNpT

**Comment by jbredwards** [comment]
I think this is a problem with unsupported optifine versions, try updating to G5

**Comment by tribes33** [comment]
Thanks that seemed to have fixed it actually, didnt realize i was on an old version
