### ISSUE TITLE
OTG Support?

### ISSUE THREAD

**Issue by Mofo50C** [jbredwards/Subaquatic#37]
Hi there, when loading an OTG world (with biomes o plenty bundle) and subaquatic, only the kelp and seagrass spawn but the ocean biomes do not. Is it possible to add support for this? Or is there a way to somehow add the biomes to OTG's biome gen? Thank you in advance

**Comment by jbredwards** [comment]
I believe this has to be added by whatever OTG configuration is selected, not something I can do from my side unfortunately
