### ISSUE TITLE
When Furnace Boats are burning fuel, nearby boats can fill with water

### ISSUE THREAD

**Issue by xJon** [jbredwards/Subaquatic#38]
![image](https://github.com/jbredwards/Subaquatic/assets/8945347/78f2c2be-a5ba-4848-9d99-fffba0989e8e)

![image](https://github.com/jbredwards/Subaquatic/assets/8945347/7a45ead3-0b73-458e-959c-93a8e4f28369)

**Comment by jbredwards** [comment]
fixed in v1.2.0
