### ISSUE TITLE
Marine Biologist water bucket trade bugged?

### ISSUE THREAD

**Issue by xJon** [jbredwards/Subaquatic#39]
(Please note the villager was spawned-in, as I couldn't find it in the first village I looked)

When trading with the Marine Biologist, there's an option for a water bucket trade:
![image](https://github.com/jbredwards/Subaquatic/assets/8945347/06afbffe-9a0c-4e79-9c35-b71e9256afd0)

Business is booming!
![image](https://github.com/jbredwards/Subaquatic/assets/8945347/5d62f3c9-469d-4095-8e84-a29a988fbaaa)

But after closing the trading window, the item texture updates to include a fish:
![image](https://github.com/jbredwards/Subaquatic/assets/8945347/336d7184-51ef-4da6-813b-77b13e884f39)

--

Also, are froglights meant to be this expensive emerald-wise?
![image](https://github.com/jbredwards/Subaquatic/assets/8945347/31b59311-150b-4133-ba73-7aa4e8ff5f53)

**Comment by jbredwards** [comment]
fixed in v1.2.0, and lowered the prices of the fish bucket & froglight trades
