### ISSUE TITLE
Inconsistent block drop results (compared to vanilla)

### ISSUE THREAD

**Issue by xJon** [jbredwards/Subaquatic#40]
- Breaking coral blocks with hand will drop the block (eventually)
- Breaking coral blocks with non silk touch tools gives you living (coloured) coral, instead of dead coral
- No way to obtain coral plants. They break and give you nothing even with silk touch

**Comment by jbredwards** [comment]
the coral plants require shears, but I'll add silk touch functionality in the next update

**Comment by jbredwards** [comment]
added config options to toggle this in v1.2.0
