### ISSUE TITLE
[Feature Request] Please separate the features of the new version of water fog as a separate mod

### ISSUE THREAD

**Issue by HaHaWTH** [jbredwards/Subaquatic#46]
When I installed the mod, the fog underwater was really amazed me :), I hope you can separate this feature as another single mod❤(also keep it in SubAquatic), and the deep blue water before Minecraft 1.13 is horrible I think:(

**Comment by jbredwards** [comment]
there's no need to make it another mod, since another mod already exists adding this (along with many other nice features) called [Aqua Acrobatics](https://legacy.curseforge.com/minecraft/mc-mods/aqua-acrobatics) :)

**Comment by HaHaWTH** [comment]
Yeah, I know Aqua Acrobatics, but the water fog of AA did not work, this is why I opened this issue:)

**Comment by HaHaWTH** [comment]
We rellay need it thx❤, the water fog is really amazing!
