### ISSUE TITLE
[Bug] Missing Textures

### ISSUE THREAD

**Issue by bluegreen1024** [jbredwards/Subaquatic#49]
When adding this mod and its dependencies to a fairly large modpack I get missing textures for water as well as seagrass and other blocks added by the mod. I've added two screenshots and the log file. I've skimmed through it and it seems to be saying something about that AssetMover can't find the assets it needs.
![2023-07-03_17 58 07](https://github.com/jbredwards/Subaquatic/assets/105248413/aac56833-0bb1-4a20-9e12-957f62bf8504)
![2023-07-03_17 58 39](https://github.com/jbredwards/Subaquatic/assets/105248413/9b8d23de-6005-4a9b-96f8-c2dfbcdff458)
[latest.log](https://github.com/jbredwards/Subaquatic/files/11941787/latest.log)

**Comment by jbredwards** [comment]
AssetMover needs a higher version of java, you can update java [here](https://adoptium.net/temurin/releases/?version=8)

**Comment by bluegreen1024** [comment]
I tried updating from the website you linked to, and I also updated Curseforge's java setting to point to the downloaded java.exe file, but I'm still getting the same issue (missing textures plus logged errors that AssetMover can't find its assets). Do you have a specific java version number that is confirmed to work, so I can double-check that I downloaded the correct one?
