### ISSUE TITLE
Crash When Placing Water into Unregistered Biome

### ISSUE THREAD

**Issue by TheMCSpacePro** [jbredwards/Subaquatic#51]
When placing water into an unregistered biome (for example, the Moon from Galacticraft), the game crashes with the following log: 
https://pastebin.com/EkZy1zZW

I think what *might* fix this is a check for biomes that weren't registered, and using a generic water color for any that are detected. The configs for all mods are default as well.

**Comment by TheMCSpacePro** [comment]
Looks like fixing this will also fix a problem with Xaero's World Map, since this error is cited in a "suppressed exception" when Xaero's World Map crashes due to landing on the moon.

That log, and issue train, seen here: [https://legacy.curseforge.com/minecraft/mc-mods/xaeros-world-map/issues/681](url)

**Comment by jbredwards** [comment]
fixed in v1.2.1
