### ISSUE TITLE
Missing Textures 

### ISSUE THREAD

**Issue by Zodiac22** [jbredwards/Subaquatic#53]
I load subaquatic and its dependencies but when i load into a world the textures are missing for the mod. All mods are up to date and java is up to date as well. [
![2023-07-15_21 45 08](https://github.com/jbredwards/Subaquatic/assets/139663371/99bd38f5-5742-4be0-b50a-dbac636f1e6b)
![2023-07-15_21 44 22](https://github.com/jbredwards/Subaquatic/assets/139663371/c0f7d5fb-e066-4b0c-a259-2db119529c16)

**Comment by MagmaSlime123** [comment]
AssetDirector issue. Restart the game. Don't know why this occurs.

**Comment by jbredwards** [comment]
this is an AssetMover issue that happens under certain conditions, installing [CensoredASM](https://www.curseforge.com/minecraft/mc-mods/lolasm) fixes it.
