### ISSUE TITLE
Another Nothirium issue.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Subaquatic#54]
See https://github.com/Meldexun/Nothirium/issues/76.

**Comment by jbredwards** [comment]
duplicate of https://github.com/jbredwards/Subaquatic/issues/33, update to v1.2.0 (which can be downloaded [here](https://modrinth.com/mod/subaquatic))

**Comment by MagmaSlime123** [comment]
Didn't know you posted onto Modrinth. My bad.
