### ISSUE TITLE
cant place biomesoplenty reed in water

### ISSUE THREAD

**Issue by xemnes** [jbredwards/Subaquatic#58]
stumbled across this issue whilst modifying bop to my own tastes, it seems reeds cant be placed in water when you right click the water surface with them (which according to the bop code is how its meant to work) when subaquatic is installed.

small request for fixing this issue since ive added my own plants to bop which behave in the same way, is there a way to fix this without specifically referencing the reed block itself? or would i need to modify subaquatic to add them?

this seems to be the code in bop that handles it, in ItemBOPPlant

> 
>                         BlockPos blockpos1 = blockpos.up();
>                         IBlockState iblockstate = worldIn.getBlockState(blockpos);
> 
>                         if (iblockstate.getMaterial() == Material.WATER && iblockstate.getValue(BlockLiquid.LEVEL).intValue() == 0 && worldIn.isAirBlock(blockpos1))
>                         {
>                             // special case for handling block placement with reeds
>                             net.minecraftforge.common.util.BlockSnapshot blocksnapshot = net.minecraftforge.common.util.BlockSnapshot.getBlockSnapshot(worldIn, blockpos1);
>                                                 
>                             worldIn.setBlockState(blockpos1, BlockBOPPlant.paging.getVariantState(BOPPlants.REED));
>                             if (net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(playerIn, blocksnapshot, net.minecraft.util.EnumFacing.UP, hand).isCanceled())
>                             {
>                                 blocksnapshot.restore(true, false);
>                                 return new ActionResult<ItemStack>(EnumActionResult.FAIL, itemStackIn);
>                             }
> 
>                             if (!playerIn.capabilities.isCreativeMode)
>                             {
>                                 itemStackIn.setCount(itemStackIn.getCount() - 1);
>                             }
> 
>                             //TODO: 1.9 playerIn.triggerAchievement(StatList.objectUseStats[Item.getIdFromItem(this)]);
>                         }

update: found a way to place them, but you need to be directly above the water at a specific height for them to place, very odd

**Comment by jbredwards** [comment]
this bug happens regardless of whether this mod is installed. Looking at BOP's code, deleting the special case in `ItemBOPPlant` and overriding `Block.canPlaceBlockOnSide` in `BlockBOPPlant` could fix it

**Comment by xemnes** [comment]
oh ok, i will have a go and see if it helps, thanks.
