### ISSUE TITLE
[Suggestion] Customizable Coral Reefs

### ISSUE THREAD

**Issue by Turkey9002** [jbredwards/Subaquatic#6]
I think it would be nice to have the option to customize what blocks can spawn on coral reefs similar to the other customization options. There's a way to do that on future versions through the use of the tags that the corals use.

**Comment by jbredwards** [comment]
added in v1.1.0, though you'll need [GroovyScript](https://legacy.curseforge.com/minecraft/mc-mods/groovyscript)
