### ISSUE TITLE
[Feature Request] Better Biome Blend Algorithm

### ISSUE THREAD

**Issue by H-QueerCoded** [jbredwards/Subaquatic#74]
It would be nice if this mod used the algorithm used by [Better Biome Blend](https://modrinth.com/mod/better-biome-blend). I tried using both mods together and looks like BBB's mixins failed.

`[22:36:24] [Server thread/WARN] [mixin]: Mixin apply for mod unknown-owner failed mixins.betterbiomeblend.json:MixinBiomeColorHelper from mod unknown-owner -> net.minecraft.world.biome.BiomeColorHelper: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PRIVATE @Overwrite method func_180285_a in mixins.betterbiomeblend.json:MixinBiomeColorHelper from mod unknown-owner cannot reduce visibiliy of PUBLIC target method`

**Comment by jbredwards** [comment]
A bit late, but this has since been fixed by MixinBooter
