### ISSUE TITLE
Biomes o plenty breaks underwater rendering (semi non-issue)

### ISSUE THREAD

**Issue by Foreck1** [jbredwards/Subaquatic#8]
Without BoP 
![image](https://user-images.githubusercontent.com/47757429/219906311-c189f675-7c28-4695-a3df-713363d0e326.png)
With BoP
![image](https://user-images.githubusercontent.com/47757429/219906409-22820863-5213-4b2b-ad32-7f4e4ae99198.png)

This can be "fixed" by toggling off BoP's own custom fog option (yes or no, no custom biome blacklist); however, this will also remove the fog for all other biomes like deserts and creepy biomes. I know this is probably not something that can be fixed from this mod's side. If there's nothing that can be done about it, feel free to close this issue.

**Comment by jbredwards** [comment]
fixed in v1.1.0
