### ISSUE TITLE
Crashed for reason (idk the reason yet)

### ISSUE THREAD

**Issue by Starexify** [jbredwards/Subaquatic#9]
I try to run a modpack with this mod and get this crash report:
https://pastebin.com/AydKnSDu

Mod Version: v1.0.1
I don't know the cause yet. So I only wanted to post this here, may help.

**Comment by Starexify** [comment]
It may be because "Future MC" already added the fish buckets in the game?

**Comment by Dakotaraptor** [comment]
I'm also getting this crash and I do not have Future MC installed

**Comment by jbredwards** [comment]
this crash is caused by AssetMover, downgrade that mod to v1.1 until the crash is fixed
